on: push
name: API Tests
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository files
        uses: actions/checkout@v1
      - name: Load test database
        run: |
          mysql -uroot -h127.0.0.1 -proot < Implementation/Database/safestreets.sql
          mysql -uroot -h127.0.0.1 -proot < Implementation/Database/test.sql
      - name: PHPUnit setup
        run: |
          wget https://phar.phpunit.de/phpunit.phar -O phpunit.phar
          sudo chmod +x phpunit.phar
          sudo mv phpunit.phar /usr/local/bin/phpunit
      - name: Run tests
        run: |
          sudo phpunit --testdox Implementation/API/tests/accounts.php
