on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
name: API Tests
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Get repository files
        uses: actions/checkout@v1
      - name: Load test database
        run: |
          mysql -uroot -h127.0.0.1 -proot < Implementation/Database/safestreets.sql
          mysql -uroot -h127.0.0.1 -proot < Implementation/Database/test.sql
      - name: Run tests
        run: |
          sudo phpunit --testdox Implementation/API/tests/accounts.php
          sudo phpunit --testdox Implementation/API/tests/reports.php